# fly.toml app configuration file generated for recipes-shashapat on 2024-10-24T14:43:16-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'recipes-shashapat'
primary_region = 'ewr'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '128mb'
cpu_kind = 'shared'
cpus = 1
